spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # 원격 접속 허용
        trace: false # h2콘솔 log에 찍기

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: never

app:
  base-url: https://giju.vercel.app

front:
  uri: ${FRONT_URI:https://giju.vercel.app}
#  uri: ${FRONT_URI:http://localhost:3000}