# 1) AWS 자격증명 (Static Provider)
cloud:
  aws:
    credentials:
      access-key: ${S3STORAGE_ACCESS_KEY}     # 환경 변수로부터 읽음
      secret-key: ${S3STORAGE_SECRET_KEY} # 환경 변수로부터 읽음
    region:
      static: ap-northeast-2 # 환경 변수 또는 기본값 :contentReference[oaicite:0]{index=0}

# 2) S3 버킷 정보
aws:
  s3:
    bucket: giju-bubble                   # 본인이 소유한 버킷 이름
    region: ap-northeast-2                # 버킷 리전

spring:
  application:
    name: giju

  profiles:
    active: local
    group:
      "prod": "prod, oauth, swagger"
      "local": "local, oauth, swagger, secret"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.springframework.security: DEBUG


order:
  targetPrice: 30000
  delivery-charge: 3000
  cleanup-expiration-minutes: 20
  delete-cycle: 30

toss:
  success_url: "/payment/success"
  fail_url: "/payment/fail"
  secret-key: ${TOSS_SECRET_KEY:asdfasdfasdfasdf}
#  secret-key: ${toss-secret:asdfasdfasdfasdf}

jwt:
  expirationtime:
    accessTime: 21600000
    refreshTime: 21600000
  secret: ${JWT_SECRET:defaultfordevalsjfielsjfinaajfowinblxiejfwoihbya}

springdoc:
  show-login-endpoint: true